config/routes.rb
Rails.application.routes.draw do

  resources :production_events, only: [:new, :create]
  resources :brands, only: [:new, :create]
  resources :webs, only: [:new, :create]
  resources :audiovisuals, only: [:new, :create]


  root to: 'frontend#index'
  
  get '/service/:category/:permalink', to: 'frontend#service', as: 'service'
  get '/presupuestos', to: 'frontend#presupuestos', as: 'presupuesto'

  devise_for :users, skip: [:registration]

  resources :admin, only: [:index]

  mount InyxCatalogRails::Engine, :at => '', as: 'catalog'

  scope :admin do
    resources :production_events, skip: [:new, :create] do
      collection do
        post '/delete', to: 'production_events#delete'
      end
    end
    resources :brands, skip: [:new, :create] do
      collection do
        post '/delete', to: 'brands#delete'
      end
    end
    resources :webs, skip: [:new, :create] do
      collection do
        post '/delete', to: 'webs#delete'
      end
    end
    resources :audiovisuals, skip: [:new, :create] do
      collection do
        post '/delete', to: 'audiovisuals#delete'
      end
    end

  	resources :users do
  		collection do
	  		post '/delete', to: 'users#delete'
  		end
  	end
  end
end

app/views/webs/_form.html.haml
= content_for(:title, "Presupuesto Online | Páginas Web")
= render 'layouts/frontend/navigation'

= render 'layouts/frontend/nav_presupuestos'

.error-msg
	- if @web.errors.count > 0
		Disculpa, existen datos inválidos en la solicitud.
		%br/
		- @web.errors.each do |name, msg|
			.error
				- if (msg != "Formato inválido") and (msg != "No puede estar en blanco")
					= msg

= simple_form_for(@web) do |f|

	.titles-inneo{style: "padding-top: 50px !important;"}
		PRESUPUESTO ONLINE
		%br/
		PÁGINAS WEB
	.separador
		= image_tag("frontend/Separador secciones.png")
	.form.web
		.row
			.col-lg-6.col-md-6.col-sm-6
				= f.input :name, label: false, input_html: { class: 'form-control',placeholder: "NOMBRE Y APELLIDO O RAZÓN SOCIAL" }
				= f.input :email, label: false, input_html: { class: 'form-control',placeholder: "CORREO ELECTRÓNICO" }
			.col-lg-6.col-md-6.col-sm-6
				= f.input :telephone, label: false, input_html: { class: 'form-control', placeholder: "NÚMERO DE TELÉFONO" }
				= f.input :brand, label: false, input_html: { class: 'form-control',placeholder: "NOMBRE DE EMPRESA O MARCA" }

		.subTitles{style:"padding-top: 30px;"}
			INFORMACIÓN DE LA EMPRESA/MARCA
		.row{style: "margin-bottom: 30px;"}
			.col-lg-6.col-md-6.col-sm-6
				= f.input :brand_description, label: false, input_html: { class: 'form-control', placeholder: "¿A QUÉ SE DEDICA TU EMPRESA/MARCA?", style: "margin-top: 10px; height: 100px;"}
			.col-lg-6.col-md-6.col-sm-6
				= f.input :brand_target, label: false, input_html: { class: 'form-control', placeholder: "DESCRIBE BREVEMENTE A QUIÉN VA DIRIGIDO (TARGET) LOS PRODUCTOS O SERVICIOS DE TU EMPRESA/MARCA", style: "margin-top: 10px; height: 100px;"}

		
		= f.input :editable_logo, label: "POSEO EL LOGO DE MI MARCA O EMPRESA EN FORMATO EDITABLE",:wrapper => :inline_checkbox 
		= f.input :audio_video_hq, label: "POSEO CONTENIDO AUDIO/VISUAL DE ALTA CALIDAD",:wrapper => :inline_checkbox 
		
		.row{style: "margin-left: 25px;"}
			.col-lg-3.col-md-3.col-sm-6.col-xs-6
				= f.input :photo, label: "FOTOGRAFÍA",:wrapper => :inline_checkbox 
				= f.input :socials, label: "PIEZAS DE DISEÑO (REDES SOCIALES)",:wrapper => :inline_checkbox 
			.col-lg-3.col-md-3.col-sm-6.col-xs-6
				= f.input :audio, label: "AUDIO",:wrapper => :inline_checkbox 
				.hidden-xs#otro_grupo1
					= check_box_tag "web[other_content_check]"
					= label_tag 'OTRO', 'OTRO'
			.col-lg-3.col-md-3.col-sm-6.col-xs-6
				= f.input :video, label: "VIDEO",:wrapper => :inline_checkbox 
			.col-lg-3.col-md-3.col-sm-6.hidden-xs#otro_grupo1
				= f.input :animation, label: "ANIMACIONES 2D/3D",:wrapper => :inline_checkbox 
		.row{style: "margin-left: 25px;"}
			.col-xs-6#otro_grupo2
				= f.input :animation, label: "ANIMACIONES 2D/3D",:wrapper => :inline_checkbox
			.col-xs-6#otro_grupo2
				= check_box_tag "web[other_content_check]"
				= label_tag 'OTRO', 'OTRO'

		= f.input :other_content, as: :string, label: false, input_html: {class: 'form-control',placeholder: "OTRO", id: "other_content",style: "margin: 0; width: 96%; margin-left: 2%;"}
			
		.subTitles
			SELECCIONA LAS CARACTERÍSTICAS QUE DESEAS PARA TU WEB:
		.row
			.col-lg-4.col-md-4.col-sm-6.col-xs-6
				= f.input :blog, label: "MÓDULO DE BLOG (NOTICIAS)",:wrapper => :inline_checkbox 
				= f.input :catalog_portfolio, label: "MÓDULO DE CATÁLOGO (PORTAFOLIO)",:wrapper => :inline_checkbox 
				= f.input :online_classes, label: "MÓDULO DE AULA VIRTUAL (CURSOS EN LÍNEA)",:wrapper => :inline_checkbox 
				= f.input :polls, label: "MÓDULO DE ENCUESTAS",:wrapper => :inline_checkbox 
				= f.input :google_apps, label: "INTEGRACIÓN CON GOOGLE APPS",:wrapper => :inline_checkbox 
				= f.input :graphic_design, label: "DISEÑO GRÁFICO EN GENERAL",:wrapper => :inline_checkbox 
				= f.input :benchmarking, label: "BENCHMARKING",:wrapper => :inline_checkbox
				#otro_grupo2{style: "margin-top:  0px !important"}
					= f.input :catalog_gallery, label: "MÓDULO DE CATÁLOGO (GALERÍA DE FOTOS/VIDEOS)",:wrapper => :inline_checkbox 
					= f.input :payment, label: "PLATAFORMA DE PAGOS (MERCADOPAGO)",:wrapper => :inline_checkbox 
					= f.input :online_reservation, label: "MÓDULO DE RESERVACIONES EN LÍNEA",:wrapper => :inline_checkbox

			.col-lg-4.col-md-4.col-sm-6.col-xs-6
				= f.input :catalog_products, label: "MÓDULO DE CATÁLOGO (PRODUCTOS/SERVICIOS)",:wrapper => :inline_checkbox 
				= f.input :e_ccommerce, label: "MÓDULO E-CCOMMERCE",:wrapper => :inline_checkbox 
				= f.input :online_chat, label: "MÓDULO DE CHAT EN LÍNEA",:wrapper => :inline_checkbox 
				= f.input :streaming_audio, label: "MÓDULO STREAMING AUDIO (RADIO)",:wrapper => :inline_checkbox 
				= f.input :marketing_strategy, label: "MARKETING DIGITAL (ESTRATEGIA/PLAN DE MARKETING",:wrapper => :inline_checkbox 
				= f.input :tv_publicity, label: "PUBLICIDAD EN TV",:wrapper => :inline_checkbox 
				#otro_grupo2{style: "margin-top: 0px !important"}
					= f.input :corp_email, label: "CORREOS CORPORATIVOS",:wrapper => :inline_checkbox 
					= f.input :marketing_manager, label: "MARKETING DIGITAL (EJECUCIÓN/COMMUNITY MANAGER",:wrapper => :inline_checkbox 
					= f.input :marketing_email, label: "E-MAIL MARKETING",:wrapper => :inline_checkbox  

			.col-lg-4.col-md-4.col-sm-6.hidden-xs#otro_grupo1
				= f.input :catalog_gallery, label: "MÓDULO DE CATÁLOGO (GALERÍA DE FOTOS/VIDEOS)",:wrapper => :inline_checkbox 
				= f.input :payment, label: "PLATAFORMA DE PAGOS (MERCADOPAGO)",:wrapper => :inline_checkbox 
				= f.input :online_reservation, label: "MÓDULO DE RESERVACIONES EN LÍNEA",:wrapper => :inline_checkbox
				= f.input :corp_email, label: "CORREOS CORPORATIVOS",:wrapper => :inline_checkbox 
				= f.input :marketing_manager, label: "MARKETING DIGITAL (EJECUCIÓN/COMMUNITY MANAGER",:wrapper => :inline_checkbox 
				= f.input :marketing_email, label: "E-MAIL MARKETING",:wrapper => :inline_checkbox  



		.subTitles
			¿DESEAS USAR ALGUNA REFERENCIA PARA EL DISEÑO DE TU WEB?
		%label Coloca la(s) dirección(es) web de tu preferencia
		.col-lg-12
			= f.input :url1, label: false, input_html: { class: 'form-control',placeholder: "URL" }
			= f.input :url2, label: false, input_html: { class: 'form-control',placeholder: "URL" }
			= f.input :url3, label: false, input_html: { class: 'form-control',placeholder: "URL" }

		.row{style: "margin-top: 25px;"}
			.col-lg-12.col-md-12.col-12
				%center
					= f.input :observations, label: false,  input_html: { class: 'form-control',placeholder: "OBSERVACIONES", style: "margin-top: 50px; height: 100px;"}	

		.form-actions
			%center
				= button_tag type: 'submit', :data => { :confirm => '¿Está seguro de querer enviar esta solicitud?' }, class: "btn-presupuesto", style: "padding-bottom: 10px; padding-top: 10px; padding-left: 20px; padding-right: 20px; border-radius: 4px !important; margin-bottom: 50px; margin-top: 50px;" do 
					ENVIAR
					%i.fa.fa-chevron-right

= render 'frontend/contact'

:javascript

	$('input[name="web[photo]"]').prop('disabled', true);
	$('input[name="web[video]"]').prop('disabled', true);
	$('input[name="web[audio]"]').prop('disabled', true);
	$('input[name="web[animation]"]').prop('disabled', true);
	$('input[name="web[socials]"]').prop('disabled', true);
	$('input[name="web[other_content_check]"]').prop('disabled', true);
	$('#other_content').hide();

	$('input[name="web[audio_video_hq]"]').change(function() {
		if ($('input:checked[name="web[audio_video_hq]"]').is(':checked')){
			$('input[name="web[photo]"]').prop('disabled', false);
			$('input[name="web[video]"]').prop('disabled', false);
			$('input[name="web[audio]"]').prop('disabled', false);
			$('input[name="web[animation]"]').prop('disabled', false);
			$('input[name="web[socials]"]').prop('disabled', false);
			$('input[name="web[other_content_check]"]').prop('disabled', false);
		}else{
			$('input[name="web[photo]"]').prop('disabled', true);
			$('input[name="web[video]"]').prop('disabled', true);
			$('input[name="web[audio]"]').prop('disabled', true);
			$('input[name="web[animation]"]').prop('disabled', true);
			$('input[name="web[socials]"]').prop('disabled', true);
			$('input[name="web[other_content_check]"]').prop('disabled', true);
		}
	});
	$('input[name="web[other_content_check]"]').change(function() {
		var otro = $('input:checked[name="web[other_content_check]"]').is(':checked')
		$('#other_content').toggle(otro);
	});

app/views/webs/_view_lg_md.html.haml
%div{ 'ng-init'=>"init(#{@objects.to_json}, '/admin/webs', '#{params[:search]}', #{@total_rows}, #{Kaminari.config.default_per_page})", "resize" => "" }
	.grid-content
		.col-lg-9.col-md-9{ style: "padding:0px;" }	
			.list-wrapper
				.panel.panel-default
					- flash.each do |name, msg|
						- if msg.is_a?(String)
							%div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'} pull-right", id: "message_alerts"}
								%button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
								= content_tag :div, msg, :id => "flash_#{name}"
					.panel-heading#list-heading
						%a.btn.btn-default.btn-action{"ng-click" => "refresh()", "ng-disabled" => "pagesItemsSelected[currentPageServer].length != 0", :title => t("admin.buttons.refresh") }
							%i.fa.fa-refresh#icon-refresh{'ng-show'=>"!loadingRefresh"}
							%i.fa.fa-refresh.fa-spin{'ng-show'=>"loadingRefresh"}
						- if can? :delete, User
							%a.btn.btn-default.btn-action{"ng-show" => "objects.length", "ng-click" => "allSelected(objects)", :title => t("admin.buttons.select_all") }
								%i.fa.fa-square-o{"ng-show" => "!btnDelete"}
								%i.fa.fa-check-square-o{ "ng-show" => "btnDelete" }	
							%a.btn.btn-default.btn-action#btn-delete{ "ng-show" => "btnDelete", "ng-click" => "destroy('¿Estas seguro de querer eliminar las solicitudes seleccionadas?')", :title => t("admin.buttons.trash") }
								%i.fa.fa-circle-o-notch.fa-spin{ 'ng-show' => "loadingDelete" }
								%i.fa.fa-trash-o{ 'ng-show' => "!loadingDelete" }
						.paginator.pull-right{ "ng-show" => "objects.length > 0"}
							%button.btn.btn-default.pull-right.hidden-xs{'disabled'=>"", style:"color:#000; margin-left:3px;"}
								Página {{currentPage+1}} de {{numberOfPages()}}
							%a.btn.btn-default.pull-right.next{ "ng-disabled"=>"currentPage >= total_objects/pageSize - 1 || loadingNext", "ng-click"=>"next()", style: "margin-left:3px" }
								%i.fa.fa-circle-o-notch.fa-spin{ 'ng-show' => "loadingNext" }
								%i.fa.fa-arrow-right{ 'ng-show' => "!loadingNext" }
							%a.btn.btn-default.pull-right.last{'ng-disabled'=>"currentPage == 0 || loadingLast", "ng-click"=>"last()"}
								%i.fa.fa-circle-o-notch.fa-spin{ 'ng-show' => "loadingLast" }
								%i.fa.fa-arrow-left{ 'ng-show' => "!loadingLast" }
					.panel-body{ style: "border-right: 1px solid #e7e7e7;" }
						#table-scroll
							%table.grid{style: "width:100%"}
								%tbody
									%tr{ class: "select-{{object.checked}}", "ng-click" => "show_object(object)", :id => "row-{{object.id}}", "ng-repeat" => "object in objects | startFrom:currentPage*pageSize | limitTo:pageSize"}
										- if can? :delete, User
											%td{ width: "1px;" }
												.checkboxFour
													%input.checkboxFourInput{:id => "check-{{object.id}}", :type => "checkbox", "ng-model" => "object.checked", "ng-click" => "selected(object); $event.stopPorpagation();" }
													%label{ for: "check-{{object.id}}" }
														%span
										%td {{ object.name }}
										%td {{ object.email }}
										%td {{ object.telephone }}
									%tr{"ng-show" => "!objects.length"}
										%td{:style => "width:100%"}
											%center
												%i.fa.fa-frown-o
												No hay Presupuestos Solicitados.
			
		.col-lg-3.col-md-3{ style: "padding:0px;"}
			.show-wrapper
				.show-head
				.show-body
					.panel.panel-default
						.panel-heading{ style: "height:55px;" }
							.actions{ "ng-show" => "object_data" }
								.title.pull-left{ style: "margin-top:6px;" }
									%i.fa.fa-user
									Solicitud de Presupuesto - {{ object_data.id }}
								- if can? :destroy, User
									= link_to "{{destroy_path(object_data.id)}}", title: t('admin.actions.delete'), :method => :delete, :data => { :confirm => '¿Estas seguro de querer eliminar esta solicitud?' }, class: "btn btn-default btn-action pull-right", "ng-show" => "object_data" do
										%i.fa.fa-remove
								= link_to "{{show_path(object_data.id)}}", title: t('admin.actions.show'), class: "btn btn-default btn-action pull-right", "ng-show" => "object_data", style: "margin-right:3px;" do
									%i.fa.fa-eye
							.actions{ "ng-show" => "!object_data", style: "margin-top:6px;" }
								%i.fa.fa-user
								Solicitud de Presupuesto
						.panel-body
							.data{ style: "height: {{windowHeight-104}}px;" }
								.attributes{ "ng-show" => "object_data" }
									%label Nombre: 
									{{object_data.name}}
									%br
									%label Correo electronico: 
									{{object_data.email}}
									%br/
									%label Numero de telefono: 
									{{object_data.telephone}}
									%br/
									
								.attributes{ "ng-show" => "!object_data"}
									%center
										No se ha seleccionado una solicitud para mostrar.
				.show-footer

app/views/webs/_view_sm_xs.html.haml
.panel.panel-default{style:"margin-top:50px"}
	.panel-header
		.paginator{ "ng-show" => "objects.length > 0"}
			%center
				Página {{currentPage+1}} de {{numberOfPages()}}
			%a.btn.btn-default.pull-right.next{ "ng-disabled"=>"currentPage >= total_objects/pageSize - 1 || loadingNext", "ng-click"=>"next()", style: "margin-left:3px" }
				%i.fa.fa-circle-o-notch.fa-spin{ 'ng-show' => "loadingNext" }
				%i.fa.fa-arrow-right{ 'ng-show' => "!loadingNext" }
			%a.btn.btn-default.pull-right.last{'ng-disabled'=>"currentPage == 0 || loadingLast", "ng-click"=>"last()"}
				%i.fa.fa-circle-o-notch.fa-spin{ 'ng-show' => "loadingLast" }
				%i.fa.fa-arrow-left{ 'ng-show' => "!loadingLast" }
	.panel-body#grid{ style: "border-right: 1px solid #e7e7e7;padding-left: 0px;padding-right: 0px;border-top-width: 36px;" }	
		%table.grid{style: "width:100%;"}
			%tbody
				%tr{ class: "select-{{object.checked}}", "ng-click" => "show_object(object)", :id => "row-{{object.id}}", "ng-repeat" => "object in objects | startFrom:currentPage*pageSize | limitTo:pageSize"}
					- if can? :delete, User
						%td{ width: "1px;" }
							.checkboxFour
								%input.checkboxFourInput{:id => "check-{{object.id}}", :type => "checkbox", "ng-model" => "object.checked", "ng-click" => "selected(object); $event.stopPorpagation();" }
								%label{ for: "check-{{object.id}}" }
									%span
					%td
						= link_to "{{show_path(object.id)}}", style: "width:100%;" do
							{{ object.name }}
				%tr{"ng-show" => "!objects.length"}
					%td{:style => "width:100%"}
						%center
							%i.fa.fa-frown-o
							No hay Solicitudes de Presupuesto.

app/views/webs/edit.html.haml
%h1 Editing web

= render 'form'

= link_to 'Show', @web
\|
= link_to 'Back', webs_path

app/views/webs/index.html.haml
= content_for(:title, "Admin - Páginas Web")

.view-lg-md.hidden-xs.hidden-sm
  = render "view_lg_md"
.view-sm-xs.hidden-lg.hidden-md
  = render "view_sm_xs"

app/views/webs/new.html.haml
= render 'form'

app/views/webs/show.html.haml
= content_for(:title, "Admin - Páginas Web | #{@web.name}")
- flash.each do |name, msg|
	- if msg.is_a?(String)
		%div.hidden-xs{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}", id:"message_alerts"}
			%button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
			= content_tag :div, msg, :id => "flash_#{name}"
%div
	.panel.panel-default{style:"margin-top:50px"}
		.panel-heading#heading-show{style:"padding-top:5px"}
			.actions
				.title.pull-left{ style: "margin-top:8px;" }
					%i.fa.fa-user
					Solicitud de Presupuesto - 
					= @web.id
				- if can? :destroy, User
					= link_to production_event_path(@web), title: t('admin.actions.delete'), :method => :delete, :data => { :confirm => '¿Estas seguro de querer eliminar esta solicitud?' }, class: "btn btn-default btn-action pull-right" do
						%i.fa.fa-remove
				- if can? :edit, User
					= link_to  edit_production_event_path(@web), title: t('admin.actions.edit'), class: "btn btn-default btn-action pull-right", style: "margin-right:3px;" do
						%i.fa.fa-pencil		

		.panel-body#body-show
			%label= 'Nombre y Apellido o Razón Social: '
			= @web.name
			%br/
			%label= 'Email: '
			= @web.email
			%br/
			%label= 'Número de Teléfono: '
			= @web.telephone
			%br/
			%label= 'Nombre de la Marca/Empresa: '
			= @web.brand
			%br/
			%label= 'Descripción de la Marca/Empresa: '
			= @web.brand_description
			%br/
			%label= 'Target de la empresa: '
			= @web.brand_target
			%br/
			%label Logo editable
			= @web.editable_logo ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
			%br/
			%label ¿Posee contenido audio/visual de alta calidad?
			- if @web.audio_video_hq 
				%i.fa.fa-check-circle
				%br/
				%div{style: "margin-left: 20px;"}
					= @web.photo ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
					%label Fotografía
					%br/
					= @web.audio ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
					%label Audio
					%br/
					= @web.video ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
					%label Video
					%br/
					= @web.animation ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
					%label Animación 2D/3D
					%br/
					= @web.socials ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
					%label Piezas de Diseño (Redes sociales)
					%br/
					- if @web.other_content != ""
						%label Otro Contenido: 
						= @web.other_content
						%br/
			- else
				%i.fa.fa-close
				%br/
			
			%label Características para la Web
			%br
			%div{style: "margin-left: 20px;"}
				= @web.blog ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
				%label Módulo de Blog (Noticias)
				%br/
				= @web.catalog_products ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
				%label Módulo de Catálogo (Productos/servicios)
				%br/
				= @web.catalog_portfolio ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
				%label Módulo de Catálogo (Portafolio)
				%br/
				= @web.catalog_gallery ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
				%label Módulo de Catálogo (Galería de fotos/videos)
				%br/
				= @web.e_ccommerce ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
				%label Módulo e-ccommerce (Tienda Virtual)
				%br/
				= @web.payment ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
				%label Módulo de pagos (MercadoPago)
				%br/
				= @web.online_classes ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
				%label Módulo de Aula Virtual (Cursos en línea)
				%br/
				= @web.online_chat ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
				%label Módulo de chat en línea
				%br/
				= @web.online_reservation ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
				%label Módulo de reservaciones en línea
				%br/
				= @web.polls ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
				%label Módulo de encuestas
				%br/
				= @web.streaming_audio ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
				%label Módulo de Streaming Audio (radio)
				%br/
				= @web.corp_email ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
				%label Correos Corporativos
				%br/
				= @web.google_apps ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
				%label Integración con Google Apps
				%br/
				= @web.marketing_strategy ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
				%label Marketing Digital (Estrategia/Plan de Marketing)
				%br/
				= @web.marketing_manager ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
				%label Marketing Digital (Ejecución/Community Manager)
				%br/
				= @web.graphic_design ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
				%label Diseño gráfico en general
				%br/
				= @web.tv_publicity ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
				%label Publicidad en TV
				%br/
				= @web.marketing_email ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
				%label E-mail Marketing
				%br/
				= @web.benchmarking ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
				%label Benchmarking
				%br/

			- if (@web.url1 != "" or @web.url2 != "" or @web.url3 != "") 
				%label Referencias Web:
				%div{style:"margin-left: 20px;"}
					- if @web.url1 != ""
						= @web.url1
						%br/
					- if @web.url2 != ""
						= @web.url2
						%br/
					- if @web.url3 != ""
						= @web.url3
						%br/

			- if @web.observations != ""
				%label Observaciones: 
				= @web.observations
				%br/