config/routes.rb
Rails.application.routes.draw do

  resources :production_events, only: [:new, :create]
  resources :brands, only: [:new, :create]
  resources :webs, only: [:new, :create]
  resources :audiovisuals, only: [:new, :create]


  root to: 'frontend#index'
  
  get '/service/:category/:permalink', to: 'frontend#service', as: 'service'
  get '/presupuestos', to: 'frontend#presupuestos', as: 'presupuesto'

  devise_for :users, skip: [:registration]

  resources :admin, only: [:index]

  mount InyxCatalogRails::Engine, :at => '', as: 'catalog'

  scope :admin do
    resources :production_events, skip: [:new, :create] do
      collection do
        post '/delete', to: 'production_events#delete'
      end
    end
    resources :brands, skip: [:new, :create] do
      collection do
        post '/delete', to: 'brands#delete'
      end
    end
    resources :webs, skip: [:new, :create] do
      collection do
        post '/delete', to: 'webs#delete'
      end
    end
    resources :audiovisuals, skip: [:new, :create] do
      collection do
        post '/delete', to: 'audiovisuals#delete'
      end
    end

  	resources :users do
  		collection do
	  		post '/delete', to: 'users#delete'
  		end
  	end
  end
end

app/models/production_event.rb
require 'elasticsearch/model'
class ProductionEvent < ActiveRecord::Base
	include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
	validates_presence_of :name, :email, :telephone, :event_type, :number_guests, :hour_begin, :hour_end, :mode, :date_event
	validate :validates_fields
	validates :email, :format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create, :message => "Formato inválido" }
  	validates :telephone, :format => { :with => /\d{11}/, :on => :create, :message => "Formato inválido" }
  	before_save :change_values_other_fields
	attr_accessor :other_event_type, :suggest, :other_service_check, :other_group_check


	def change_values_other_fields
		self.place = "SUGERIR" if self.suggest == "1" 
		self.other_group = "" if self.other_group_check.nil?
		self.other_service = "" if self.other_service_check.nil?
		self.event_type = self.other_event_type if self.event_type == "OTRO"
	end

	def validates_fields
		errors.add(:errors, "Debe indicar el tipo de evento") if (self.event_type == "OTRO" and self.other_event_type == "")
		errors.add(:errors, "Debe indicar el servicio adicional") if (self.other_service_check == "1" and self.other_service == "")
		errors.add(:errors, "Debe indicar el grupo") if (self.other_group_check == "1" and self.other_group == "")
		errors.add(:errors, "Debe indicar el lugar del evento") if (self.place == "" and self.suggest.nil?)
		errors.add(:errors, "Debe indicar la hora de Inicio" ) if self.hour_begin == "HORA DE INICIO"
		errors.add(:errors, "Debe indicar la hora de Culminación" ) if self.hour_end == "HORA DE CULMINACIÓN"
		errors.add(:errors, "La fecha del Evento es inválida") if self.date_event < Date.today
		errors.add(:errors, "La cantidad de invitados es inválida") if self.number_guests.to_i < 1
	end

	def self.index(current_user)
    ProductionEvent.order("created_at DESC")
  end

  #params[:search] is true
  def self.index_search(objects, current_user)
    objects.order("created_at DESC")
  end

  #params[:search] is true
  def self.index_total(objects, current_user)
    objects.count
  end

  def self.route_index
    "/admin/production_events"
  end

  def index_elasticsearch_document
    self.__elasticsearch__.index_document
  end

  def self.multiple_destroy(ids, current_user)
    ProductionEvent.destroy ids
  end
end

app/controllers/production_events_controller.rb
class ProductionEventsController < ApplicationController
  layout :resolve_layout
  before_action :set_production_event, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource except: [:new,:create]


  # GET /production_events/1
  # GET /production_events/1.json
  def show
    @event = ProductionEvent.find(params[:id])
  end

  # GET /production_events/new
  def new
    @production_event = ProductionEvent.new
  end

  # GET /production_events/1/edit
  def edit
    @event = ProductionEvent.find(params[:id])
  end

  # POST /production_events
  # POST /production_events.json
  def create
    @production_event = ProductionEvent.new(production_event_params)

    respond_to do |format|
      if @production_event.save
        format.html { redirect_to '/presupuestos', notice: 'SU SOLICITUD PARA PRESUPUESTO DE PRODUCCIÓN DE EVENTOS/DIVOZ HA SIDO ENVIADA.' }
        format.json { render :show, status: :created, location: @production_event }
        BudgetMailer.budget_email(production_event_params, "Producción de Eventos", "http://localhost:3000/admin/production_events/#{ProductionEvent.last.id}").deliver_now
      else
        format.html { render :new }
        format.json { render json: @production_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /production_events/1
  # PATCH/PUT /production_events/1.json
  def update
    respond_to do |format|
      if @production_event.update(production_event_params)
        format.html { redirect_to @production_event, notice: 'Production event was successfully updated.' }
        format.json { render :show, status: :ok, location: @production_event }
      else
        format.html { render :edit }
        format.json { render json: @production_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /production_events/1
  # DELETE /production_events/1.json
  def destroy
    @production_event.destroy
    respond_to do |format|
      format.html { redirect_to production_events_url, notice: 'Production event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_production_event
      @production_event = ProductionEvent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def production_event_params
      params.require(:production_event).permit(:date_event, :name, :email, :telephone, :event_type, :place, :number_guests, :hour_begin, :hour_end, :mode, :sound, :video, :confetti, :lights, :sparkles, :led_robot, :led_screens, :fireworks, :strippers, :photoshoot, :garotas, :stilts, :other_service, :strings, :drums, :mariachi, :vallenato, :other_group, :comment, :other_event_type, :suggest, :other_service_check, :other_group_check)
    end

    def resolve_layout
      case action_name
      when "destroy", "update", "edit", "show", "index"
        'admin/application'
      else
        'frontend/application'
      end
      end
end

app/helpers/production_events_helper.rb
module ProductionEventsHelper
end

app/views/production_events/_view_lg_md.html.haml
%div{ 'ng-init'=>"init(#{@objects.to_json}, '/admin/production_events', '#{params[:search]}', #{@total_rows}, #{Kaminari.config.default_per_page})", "resize" => "" }
	.grid-content
		.col-lg-9.col-md-9{ style: "padding:0px;" }	
			.list-wrapper
				.panel.panel-default
					- flash.each do |name, msg|
						- if msg.is_a?(String)
							%div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'} pull-right", id: "message_alerts"}
								%button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
								= content_tag :div, msg, :id => "flash_#{name}"
					.panel-heading#list-heading
						%a.btn.btn-default.btn-action{"ng-click" => "refresh()", "ng-disabled" => "pagesItemsSelected[currentPageServer].length != 0", :title => t("admin.buttons.refresh") }
							%i.fa.fa-refresh#icon-refresh{'ng-show'=>"!loadingRefresh"}
							%i.fa.fa-refresh.fa-spin{'ng-show'=>"loadingRefresh"}
						- if can? :delete, User
							%a.btn.btn-default.btn-action{"ng-show" => "objects.length", "ng-click" => "allSelected(objects)", :title => t("admin.buttons.select_all") }
								%i.fa.fa-square-o{"ng-show" => "!btnDelete"}
								%i.fa.fa-check-square-o{ "ng-show" => "btnDelete" }	
							%a.btn.btn-default.btn-action#btn-delete{ "ng-show" => "btnDelete", "ng-click" => "destroy('¿Estas seguro de querer eliminar las solicitudes seleccionadas?')", :title => t("admin.buttons.trash") }
								%i.fa.fa-circle-o-notch.fa-spin{ 'ng-show' => "loadingDelete" }
								%i.fa.fa-trash-o{ 'ng-show' => "!loadingDelete" }
						.paginator.pull-right{ "ng-show" => "objects.length > 0"}
							%button.btn.btn-default.pull-right.hidden-xs{'disabled'=>"", style:"color:#000; margin-left:3px;"}
								Página {{currentPage+1}} de {{numberOfPages()}}
							%a.btn.btn-default.pull-right.next{ "ng-disabled"=>"currentPage >= total_objects/pageSize - 1 || loadingNext", "ng-click"=>"next()", style: "margin-left:3px" }
								%i.fa.fa-circle-o-notch.fa-spin{ 'ng-show' => "loadingNext" }
								%i.fa.fa-arrow-right{ 'ng-show' => "!loadingNext" }
							%a.btn.btn-default.pull-right.last{'ng-disabled'=>"currentPage == 0 || loadingLast", "ng-click"=>"last()"}
								%i.fa.fa-circle-o-notch.fa-spin{ 'ng-show' => "loadingLast" }
								%i.fa.fa-arrow-left{ 'ng-show' => "!loadingLast" }
					.panel-body{ style: "border-right: 1px solid #e7e7e7;" }
						#table-scroll
							%table.grid{style: "width:100%"}
								%tbody
									%tr{ class: "select-{{object.checked}}", "ng-click" => "show_object(object)", :id => "row-{{object.id}}", "ng-repeat" => "object in objects | startFrom:currentPage*pageSize | limitTo:pageSize"}
										- if can? :delete, User
											%td{ width: "1px;" }
												.checkboxFour
													%input.checkboxFourInput{:id => "check-{{object.id}}", :type => "checkbox", "ng-model" => "object.checked", "ng-click" => "selected(object); $event.stopPorpagation();" }
													%label{ for: "check-{{object.id}}" }
														%span
										%td {{ object.name }}
										%td {{ object.email }}
										%td {{ object.telephone }}
									%tr{"ng-show" => "!objects.length"}
										%td{:style => "width:100%"}
											%center
												%i.fa.fa-frown-o
												No hay Presupuestos Solicitados.
			
		.col-lg-3.col-md-3{ style: "padding:0px;"}
			.show-wrapper
				.show-head
				.show-body
					.panel.panel-default
						.panel-heading{ style: "height:55px;" }
							.actions{ "ng-show" => "object_data" }
								.title.pull-left{ style: "margin-top:6px;" }
									%i.fa.fa-user
									Solicitud de Presupuesto - {{ object_data.id }}
								- if can? :destroy, User
									= link_to "{{destroy_path(object_data.id)}}", title: t('admin.actions.delete'), :method => :delete, :data => { :confirm => '¿Estas seguro de querer eliminar esta solicitud?' }, class: "btn btn-default btn-action pull-right", "ng-show" => "object_data" do
										%i.fa.fa-remove
								= link_to "{{show_path(object_data.id)}}", title: t('admin.actions.show'), class: "btn btn-default btn-action pull-right", "ng-show" => "object_data", style: "margin-right:3px;" do
									%i.fa.fa-eye
							.actions{ "ng-show" => "!object_data", style: "margin-top:6px;" }
								%i.fa.fa-user
								Solicitud de Presupuesto
						.panel-body
							.data{ style: "height: {{windowHeight-104}}px;" }
								.attributes{ "ng-show" => "object_data" }
									%label Nombre: 
									{{object_data.name}}
									%br
									%label Correo electronico: 
									{{object_data.email}}
									%br/
									%label Numero de telefono: 
									{{object_data.telephone}}
									%br/
									%label Tipo de Evento: 
									{{object_data.event_type}}
									%br/
									%label Lugar: 
									{{object_data.place}}
									%br/
									%label Cantidad de Invitados: 
									{{object_data.number_guests}}
									%br/
									%label Hora de inicio: 
									{{object_data.hour_begin}}
									%br/
									%label Hora de culminacion: 
									{{object_data.hour_end}}
									%br/
									
								.attributes{ "ng-show" => "!object_data"}
									%center
										No se ha seleccionado una solicitud para mostrar.
				.show-footer

app/views/production_events/_view_sm_xs.html.haml
.panel.panel-default{style:"margin-top:50px"}
	.panel-header
		.paginator{ "ng-show" => "objects.length > 0"}
			%center
				Página {{currentPage+1}} de {{numberOfPages()}}
			%a.btn.btn-default.pull-right.next{ "ng-disabled"=>"currentPage >= total_objects/pageSize - 1 || loadingNext", "ng-click"=>"next()", style: "margin-left:3px" }
				%i.fa.fa-circle-o-notch.fa-spin{ 'ng-show' => "loadingNext" }
				%i.fa.fa-arrow-right{ 'ng-show' => "!loadingNext" }
			%a.btn.btn-default.pull-right.last{'ng-disabled'=>"currentPage == 0 || loadingLast", "ng-click"=>"last()"}
				%i.fa.fa-circle-o-notch.fa-spin{ 'ng-show' => "loadingLast" }
				%i.fa.fa-arrow-left{ 'ng-show' => "!loadingLast" }
	.panel-body#grid{ style: "border-right: 1px solid #e7e7e7;padding-left: 0px;padding-right: 0px;border-top-width: 36px;" }	
		%table.grid{style: "width:100%;"}
			%tbody
				%tr{ class: "select-{{object.checked}}", "ng-click" => "show_object(object)", :id => "row-{{object.id}}", "ng-repeat" => "object in objects | startFrom:currentPage*pageSize | limitTo:pageSize"}
					- if can? :delete, User
						%td{ width: "1px;" }
							.checkboxFour
								%input.checkboxFourInput{:id => "check-{{object.id}}", :type => "checkbox", "ng-model" => "object.checked", "ng-click" => "selected(object); $event.stopPorpagation();" }
								%label{ for: "check-{{object.id}}" }
									%span
					%td
						= link_to "{{show_path(object.id)}}", style: "width:100%;" do
							{{ object.name }}
				%tr{"ng-show" => "!objects.length"}
					%td{:style => "width:100%"}
						%center
							%i.fa.fa-frown-o
							No hay Solicitudes de Presupuesto.

app/views/production_events/edit.html.haml
%h1 Editing production_event

= render 'form'

= link_to 'Show', @production_event
\|
= link_to 'Back', production_events_path

app/views/production_events/index.html.haml
= content_for(:title, "Admin - Produccion de Eventos")

.view-lg-md.hidden-xs.hidden-sm
  = render "view_lg_md"
.view-sm-xs.hidden-lg.hidden-md
  = render "view_sm_xs"
          

    

app/views/production_events/new.html.haml
= render 'form'

app/views/production_events/show.html.haml
= content_for(:title, "Admin - Producción de Eventos | #{@event.name}")
- flash.each do |name, msg|
	- if msg.is_a?(String)
		%div.hidden-xs{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}", id:"message_alerts"}
			%button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
			= content_tag :div, msg, :id => "flash_#{name}"
%div
	.panel.panel-default{style:"margin-top:50px"}
		.panel-heading#heading-show{style:"padding-top:5px"}
			.actions
				.title.pull-left{ style: "margin-top:8px;" }
					%i.fa.fa-user
					Solicitud de Presupuesto - 
					= @event.id
				- if can? :destroy, User
					= link_to production_event_path(@event), title: t('admin.actions.delete'), :method => :delete, :data => { :confirm => '¿Estas seguro de querer eliminar este usuario?' }, class: "btn btn-default btn-action pull-right" do
						%i.fa.fa-remove
				- if can? :edit, User
					= link_to  edit_production_event_path(@event), title: t('admin.actions.edit'), class: "btn btn-default btn-action pull-right", style: "margin-right:3px;" do
						%i.fa.fa-pencil		

		.panel-body#body-show
			%label= 'Nombre y Apellido o Razón Social: '
			= @event.name
			%br/
			%label= 'Email: '
			= @event.email
			%br/
			%label= 'Número de Teléfono: '
			= @event.telephone
			%br/
			%label= 'Tipo de Evento: '
			= @event.event_type
			%br/
			%label= 'Lugar: '
			= @event.place
			%br/
			%label= 'Cantidad de Invitados: '
			= @event.number_guests
			%br/
			%label= 'Fecha del Evento: '
			= @event.date_event
			%br/
			%label= 'Horas del evento: '
			De 
			= @event.hour_begin
			a
			= @event.hour_end
			%br/
			%label= 'Tipo de Evento: '
			= @event.event_type
			%br/
			%label= 'Modalidad: '
			= @event.mode
			%br/
			%label Servicios Solicitados
			%br/
			%div{style: "margin-left: 20px;"}
				= @event.sound ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
				%label Sonido
				%br/
				= @event.lights ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
				%label Iluminación
				%br/
				= @event.led_screens ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
				%label Pantallas LED
				%br/
				= @event.photoshoot ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
				%label Fotografía
				%br/
				= @event.video ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
				%label Video
				%br/
				= @event.sparkles ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
				%label Chispas
				%br/
				= @event.fireworks ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
				%label Fuegos artificiales
				%br/
				= @event.garotas ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
				%label Garotas/Garotos
				%br/
				= @event.confetti ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
				%label Cañón de Confeti
				%br/
				= @event.led_robot ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
				%label Robot LED
				%br/
				= @event.strippers ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
				%label Strippers
				%br/
				= @event.stilts ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
				%label Zanqueros
				%br/
				- if @event.other_service != ""
					%label Otro Servicio: 
					= @event.other_service
					%br/

			%label Agrupaciones Musicales
			%br
			%div{style: "margin-left: 20px;"}
				= @event.strings ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
				%label Cuarteto de Cuerdas
				%br/
				= @event.drums ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
				%label Tambor
				%br/
				= @event.mariachi ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
				%label Mariachi
				%br/
				= @event.vallenato ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
				%label Vallenato
				%br/
				- if @event.other_group != ""
					%label Otro grupo: 
					= @event.other_group
					%br/
			- if @event.comment != ""
				%label Comentario: 
				= @event.comment
				%br/