config/routes.rb
Rails.application.routes.draw do

  resources :production_events, only: [:new, :create]
  resources :brands, only: [:new, :create]
  resources :webs, only: [:new, :create]
  resources :audiovisuals, only: [:new, :create]


  root to: 'frontend#index'
  
  get '/service/:category/:permalink', to: 'frontend#service', as: 'service'
  get '/presupuestos', to: 'frontend#presupuestos', as: 'presupuesto'

  devise_for :users, skip: [:registration]

  resources :admin, only: [:index]

  mount InyxCatalogRails::Engine, :at => '', as: 'catalog'

  scope :admin do
    resources :production_events, skip: [:new, :create] do
      collection do
        post '/delete', to: 'production_events#delete'
      end
    end
    resources :brands, skip: [:new, :create] do
      collection do
        post '/delete', to: 'brands#delete'
      end
    end
    resources :webs, skip: [:new, :create] do
      collection do
        post '/delete', to: 'webs#delete'
      end
    end
    resources :audiovisuals, skip: [:new, :create] do
      collection do
        post '/delete', to: 'audiovisuals#delete'
      end
    end

  	resources :users do
  		collection do
	  		post '/delete', to: 'users#delete'
  		end
  	end
  end
end

app/controllers/frontend_controller.rb
class FrontendController < ApplicationController
	layout 'layouts/frontend/application'

	def index
		Location.add(request.remote_ip)

		@produccion= InyxCatalogRails::Catalog.where(category: "PRODUCCIÓN DE EVENTOS").first
		@branding= InyxCatalogRails::Catalog.where(category: "BRANDING").first
		@marketing= InyxCatalogRails::Catalog.where(category: "MARKETING AUDIOVISUAL").first
	end

	def service
		@catalogo = InyxCatalogRails::Catalog.where(category: (params[:category].gsub("-", " ").mb_chars.upcase))
		@attachments = @catalogo.find_by_permalink(params[:permalink]).attachments.where(public: true).order(:created_at).reverse_order

		if @catalogo.first.category ==  "PRODUCCIÓN DE EVENTOS"
			@text = "Promovemos la innovación contando con el mejor talento humano que convertirá tu evento en una experiencia inolvidable."
		elsif @catalogo.first.category ==  "BRANDING"
			@text = "Resaltamos el poder de tu marca utilizando estrategias integrales que fortalecen tu imagen y te diferencian en el mercado."
		elsif @catalogo.first.category ==  "MARKETING AUDIOVISUAL"
			@text = "Nuestro talentoso equipo quiere dar a conocer tus ideas, aprovechándolas al máximo y creando campañas atractivas a través de contenidos originales."
		elsif @catalogo.first.category ==  "DIVOZ"
			@text = "Únete a nuestros felices clientes y permítenos ser parte de tu historia."
		end
		
	end
	
	def presupuestos
		@brand = Brand.new
		@production_event = ProductionEvent.new
	end


end

app/helpers/frontend_helper.rb
module FrontendHelper
end

app/views/layouts/frontend/_head.html.haml
%head
	%meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
	= stylesheet_link_tag 'frontend/application', media: 'all', 'data-turbolinks-track' => true
	%link{:href => "http://fonts.googleapis.com/css?family=Roboto:300,700,400", :rel => "stylesheet", :type => "text/css"}/
	= javascript_include_tag 'frontend/application', 'data-turbolinks-track' => true
	= csrf_meta_tags
	= favicon_link_tag 'frontend/favicon.png'
	%meta{:content => "summary", :property => "twitter:card"}/
	%meta{:content => "http://www.inneoproducciones.com/", :property => "twitter:url"}/
	%meta{:content => "@inneopro", :property => "twitter:site"}/
	%meta{:content => "es_ES", :property => "og:locale"}/
	%meta{:content => "article", :property => "og:type"}/
	%meta{:content => "Inneo Producciones - Marketing Audiovisual", :property => "og:site_name"}/
	%meta{:content => "noodp,noydir", :name => "robots"}/
	%meta{:content => "Somos una productora de eventos, hacemos branding, marketing, talento musical con nuestra banda DIVOZ, Produccion audiovisual y de eventos en Venezuela", :name => "description"}
	%meta{:content => "noodp,noydir", :name => "robots"}/
	%title INNEO PRODUCCIONES - MARKETING AUDIOVISUAL EN VENEZUELA
	:javascript
		(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

		ga('create', 'UA-64028504-1', 'auto');
		ga('send', 'pageview');

app/views/layouts/frontend/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/frontend/_nav_presupuestos.html.haml
%ul.nav.nav-pills
	%li.hidden-lg.hidden-md.hidden-sm#btn-xs{ class: "#{'active' if params[:controller] == 'production_events'}" } 
		= link_to new_production_event_path do
			DIVOZ/PRODUCCIÓN
			%br/
			DE EVENTOS
	%li.hidden-xs#btn-lg{ class: "#{'active' if params[:controller] == 'production_events'}"} 
		= link_to new_production_event_path do
			DIVOZ/PRODUCCIÓN DE EVENTOS
	%li#btn-lg{ class: "#{'active' if params[:controller] == 'brands'}" }
		= link_to new_brand_path do
			BRANDING
	%li.hidden-lg.hidden-md.hidden-sm#btn-xs{ class: "#{'active' if params[:controller] == 'audiovisuals'}" }
		= link_to new_audiovisual_path do
			MARKETING
			%br/
			AUDIOVISUAL
	%li.hidden-xs#btn-lg{ class: "#{'active' if params[:controller] == 'audiovisuals'}" }
		= link_to new_audiovisual_path do
			MARKETING AUDIOVISUAL
	%li#btn-lg{ class: "#{'active' if params[:controller] == 'webs'}" }
		= link_to new_web_path do
			PÁGINAS WEB

app/views/layouts/frontend/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-static-top#front-navbar
	.container-fluid
		.navbar-header
			%button.navbar-toggle.collapsed{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
				%span.sr-only Toggle navigation
				%span.icon-bar
				%span.icon-bar
				%span.icon-bar
			.navbar-brand
				= link_to "/" do 
					=image_tag "frontend/Logotipo footer.png", width: "100px" 
		#bs-example-navbar-collapse-1.collapse.navbar-collapse
			- if controller.action_name == "index"
				%ul.nav.navbar-nav.navbar-right
					%li.bar
						%a{:href => "#home"}	HOME
					%li.bar
						%a{:href => "#services"} SERVICIOS
					%li.bar
						%a{:href => "#contact"} CONTACTOS
			- else	
				= render 'layouts/frontend/navigation_services'
			
				

app/views/layouts/frontend/_navigation_services.html.haml
%ul.nav.navbar-nav.navbar-right
	%li.bar{style: "z-index: 10;"}
		= link_to "HOME", root_path(anchor: "home"), class: "external"
	%li.dropdown.hidden-xs.hidden-sm
		%a.dropdown-tag{:href => "#services"}
			SERVICIOS
			.arrow-navbar.hidden-xs.hidden-sm
				= image_tag ("frontend/flechas-navbar.png")
		%ul.dropdown-menu.dropdown-nav{:role => "menu"}
			%li
				= link_to "PRODUCCIÓN DE EVENTOS", service_path(category: "producción-de-eventos", permalink: "fotografia"), class: "external"
			.divider
			%li
				= link_to "MARKETING AUDIOVISUAL", service_path(category: "marketing-audiovisual" , permalink: "animacion-2d-y-3d"), class: "external"
			.divider
			%li
				= link_to "BRANDING", service_path(category: "branding", permalink: "identidad-corporativa"), class: "external"
			.divider
			%li
				= link_to "DIVOZ", service_path(category: "divoz", permalink: "divoz"), class: "external"
	%li.bar.hidden-lg.hidden-md
		= link_to "SERVICIOS", root_path(anchor: "services"), class: "external"
	%li.bar
		%A{href: "#contactos"} CONTACTOS

app/views/layouts/frontend/application.html.haml
!!!
%html
  = render 'layouts/frontend/head' 
  %body
    %header
      =# render 'layouts/frontend/navigation'
      = #render 'layouts/frontend/messages'
    = yield