config/routes.rb
Rails.application.routes.draw do

  resources :production_events, only: [:new, :create]
  resources :brands, only: [:new, :create]
  resources :webs, only: [:new, :create]
  resources :audiovisuals, only: [:new, :create]


  root to: 'frontend#index'
  
  get '/service/:category/:permalink', to: 'frontend#service', as: 'service'
  get '/presupuestos', to: 'frontend#presupuestos', as: 'presupuesto'

  devise_for :users, skip: [:registration]

  resources :admin, only: [:index]

  mount InyxCatalogRails::Engine, :at => '', as: 'catalog'

  scope :admin do
    resources :production_events, skip: [:new, :create] do
      collection do
        post '/delete', to: 'production_events#delete'
      end
    end
    resources :brands, skip: [:new, :create] do
      collection do
        post '/delete', to: 'brands#delete'
      end
    end
    resources :webs, skip: [:new, :create] do
      collection do
        post '/delete', to: 'webs#delete'
      end
    end
    resources :audiovisuals, skip: [:new, :create] do
      collection do
        post '/delete', to: 'audiovisuals#delete'
      end
    end

  	resources :users do
  		collection do
	  		post '/delete', to: 'users#delete'
  		end
  	end
  end
end

app/models/brand.rb
require 'elasticsearch/model'
class Brand < ActiveRecord::Base

  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  validates_presence_of :name, :email, :telephone, :brand_name
  validate :validates_fields
  validates :email, :format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create, :message => "Formato inválido" }
  validates :telephone, :format => { :with => /\d{11}/, :on => :create, :message => "Formato inválido" }
  before_save :change_values_other_fields
  attr_accessor :other_corp_check, :other_pop_check, :backing_check, :backing_height, :backing_width, :other_printed_check


  def change_values_other_fields
    self.other_corp = "" if self.other_corp_check.nil?
    self.other_pop = "" if self.other_pop_check.nil?
    self.other_printed = "" if self.other_printed_check.nil?
    self.backing = "#{self.backing_height} x #{self.backing_width}" if self.backing_check == "1"
  end

  def validates_fields
    errors.add(:errors, "Debe indicar el servicio adicional de Identidad Corporativa") if (self.other_corp_check == "1" and self.other_corp == "")
    errors.add(:errors, "Debe indicar el servicio adicional de Material P.O.P") if (self.other_pop_check == "1" and self.other_pop == "")
    errors.add(:errors, "Debe indicar el servicio adicional de Material Impreso") if (self.other_printed_check == "1" and self.other_printed == "")
    errors.add(:errors, "Debe indicar las dimensiones del Backing") if (self.backing_check == "1" and ((self.backing_height == "" or self.backing_width == "") or (self.backing_width.to_i <1 or self.backing_height.to_i <1)))
  end

  def self.index(current_user)
    Brand.order("created_at DESC")
  end

  #params[:search] is true
  def self.index_search(objects, current_user)
    objects.order("created_at DESC")
  end

  #params[:search] is true
  def self.index_total(objects, current_user)
    objects.count
  end

  def self.route_index
    "/admin/brands"
  end

  def index_elasticsearch_document
    self.__elasticsearch__.index_document
  end

  def self.multiple_destroy(ids, current_user)
    Brand.destroy ids
  end

end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :set_brand, only: [:show, :edit, :update, :destroy]
  layout :resolve_layout
  before_filter :authenticate_user!, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource except: [:new,:create]

  # GET /brands
  # GET /brands.json


  # GET /brands/1
  # GET /brands/1.json
  def show
    @brand = Brand.find(params[:id])
  end

  # GET /brands/new
  def new
    @brand = Brand.new
  end

  # GET /brands/1/edit
  def edit
    @brand = Brand.find(params[:id])
  end

  # POST /brands
  # POST /brands.json
  def create
    @brand = Brand.new(brand_params)

    respond_to do |format|
      if @brand.save
        format.html { redirect_to '/presupuestos', notice: 'SU SOLICITUD PARA PRESUPUESTO DE BRANDING HA SIDO ENVIADA.' }
        format.json { render :show, status: :created, location: @brand }
        BudgetMailer.budget_email(brand_params, "Branding", "http://localhost:3000/admin/brands/#{Brand.last.id}").deliver_now
      else
        format.html { render :new }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brands/1
  # PATCH/PUT /brands/1.json
  def update
    respond_to do |format|
      if @brand.update(brand_params)
        format.html { redirect_to @brand, notice: 'Brand was successfully updated.' }
        format.json { render :show, status: :ok, location: @brand }
      else
        format.html { render :edit }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1
  # DELETE /brands/1.json
  def destroy
    @brand.destroy
    respond_to do |format|
      format.html { redirect_to "/admin/brands", notice: 'Brand was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand
      @brand = Brand.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brand_params
      params.require(:brand).permit( :name, :email, :telephone, :brand_name, :logo, :tdp, :envelope, :folder, :email_signature, :products_menu, :brand_menu, :letterhead, :notebook, :carnet, :bill, :uniform, :brochure, :other_corp, :pens, :calendars, :mouse_pad, :disposable_ids, :resin_ids, :mugs, :coolers, :key_chain, :hats, :t_shirts, :stickers, :other_pop, :poster_half_a4, :poster_quarter_a4, :poster, :press_full,:press_double, :press_half, :press_quarter, :press_eights, :pennon, :banner, :backing, :other_printed , :other_corp_check, :other_pop_check, :backing_check, :backing_height, :backing_width, :other_printed_check)
    end

    def resolve_layout
      case action_name
      when "destroy", "update", "edit", "show", "index"
        'admin/application'
      else
        'frontend/application'
      end
    end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/views/brands/_view_lg_md.html.haml
%div{ 'ng-init'=>"init(#{@objects.to_json}, '/admin/brands', '#{params[:search]}', #{@total_rows}, #{Kaminari.config.default_per_page})", "resize" => "" }
	.grid-content
		.col-lg-9.col-md-9{ style: "padding:0px;" }	
			.list-wrapper
				.panel.panel-default
					- flash.each do |name, msg|
						- if msg.is_a?(String)
							%div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'} pull-right", id: "message_alerts"}
								%button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
								= content_tag :div, msg, :id => "flash_#{name}"
					.panel-heading#list-heading
						%a.btn.btn-default.btn-action{"ng-click" => "refresh()", "ng-disabled" => "pagesItemsSelected[currentPageServer].length != 0", :title => t("admin.buttons.refresh") }
							%i.fa.fa-refresh#icon-refresh{'ng-show'=>"!loadingRefresh"}
							%i.fa.fa-refresh.fa-spin{'ng-show'=>"loadingRefresh"}
						- if can? :delete, User
							%a.btn.btn-default.btn-action{"ng-show" => "objects.length", "ng-click" => "allSelected(objects)", :title => t("admin.buttons.select_all") }
								%i.fa.fa-square-o{"ng-show" => "!btnDelete"}
								%i.fa.fa-check-square-o{ "ng-show" => "btnDelete" }	
							%a.btn.btn-default.btn-action#btn-delete{ "ng-show" => "btnDelete", "ng-click" => "destroy('¿Estas seguro de querer eliminar las solicitudes seleccionadas?')", :title => t("admin.buttons.trash") }
								%i.fa.fa-circle-o-notch.fa-spin{ 'ng-show' => "loadingDelete" }
								%i.fa.fa-trash-o{ 'ng-show' => "!loadingDelete" }
						.paginator.pull-right{ "ng-show" => "objects.length > 0"}
							%button.btn.btn-default.pull-right.hidden-xs{'disabled'=>"", style:"color:#000; margin-left:3px;"}
								Página {{currentPage+1}} de {{numberOfPages()}}
							%a.btn.btn-default.pull-right.next{ "ng-disabled"=>"currentPage >= total_objects/pageSize - 1 || loadingNext", "ng-click"=>"next()", style: "margin-left:3px" }
								%i.fa.fa-circle-o-notch.fa-spin{ 'ng-show' => "loadingNext" }
								%i.fa.fa-arrow-right{ 'ng-show' => "!loadingNext" }
							%a.btn.btn-default.pull-right.last{'ng-disabled'=>"currentPage == 0 || loadingLast", "ng-click"=>"last()"}
								%i.fa.fa-circle-o-notch.fa-spin{ 'ng-show' => "loadingLast" }
								%i.fa.fa-arrow-left{ 'ng-show' => "!loadingLast" }
					.panel-body{ style: "border-right: 1px solid #e7e7e7;" }
						#table-scroll
							%table.grid{style: "width:100%"}
								%tbody
									%tr{ class: "select-{{object.checked}}", "ng-click" => "show_object(object)", :id => "row-{{object.id}}", "ng-repeat" => "object in objects | startFrom:currentPage*pageSize | limitTo:pageSize"}
										- if can? :delete, User
											%td{ width: "1px;" }
												.checkboxFour
													%input.checkboxFourInput{:id => "check-{{object.id}}", :type => "checkbox", "ng-model" => "object.checked", "ng-click" => "selected(object); $event.stopPorpagation();" }
													%label{ for: "check-{{object.id}}" }
														%span
										%td {{ object.name }}
										%td {{ object.email }}
										%td {{ object.telephone }}
										%td {{ object.brand_name }}
									%tr{"ng-show" => "!objects.length"}
										%td{:style => "width:100%"}
											%center
												%i.fa.fa-frown-o
												No hay Presupuestos Solicitados.
			
		.col-lg-3.col-md-3{ style: "padding:0px;"}
			.show-wrapper
				.show-head
				.show-body
					.panel.panel-default
						.panel-heading{ style: "height:55px;" }
							.actions{ "ng-show" => "object_data" }
								.title.pull-left{ style: "margin-top:6px;" }
									%i.fa.fa-user
									Solicitud de Presupuesto - {{ object_data.id }}
								- if can? :destroy, User
									= link_to "{{destroy_path(object_data.id)}}", title: t('admin.actions.delete'), :method => :delete, :data => { :confirm => '¿Estas seguro de querer eliminar esta solicitud?' }, class: "btn btn-default btn-action pull-right", "ng-show" => "object_data" do
										%i.fa.fa-remove
								= link_to "{{show_path(object_data.id)}}", title: t('admin.actions.show'), class: "btn btn-default btn-action pull-right", "ng-show" => "object_data", style: "margin-right:3px;" do
									%i.fa.fa-eye
							.actions{ "ng-show" => "!object_data", style: "margin-top:6px;" }
								%i.fa.fa-user
								Solicitud de Presupuesto
						.panel-body
							.data{ style: "height: {{windowHeight-104}}px;" }
								.attributes{ "ng-show" => "object_data" }
									%label Nombre: 
									{{object_data.name}}
									%br
									%label Correo electronico: 
									{{object_data.email}}
									%br/
									%label Numero de telefono: 
									{{object_data.telephone}}
									%br/
									%label Nombre de Marca o Empresa: 
									{{object_data.brand_name}}
									%br/
									
								.attributes{ "ng-show" => "!object_data"}
									%center
										No se ha seleccionado una solicitud para mostrar.
				.show-footer

app/views/brands/_view_sm_xs.html.haml
.panel.panel-default{style:"margin-top:50px"}
	.panel-header
		.paginator{ "ng-show" => "objects.length > 0"}
			%center
				Página {{currentPage+1}} de {{numberOfPages()}}
			%a.btn.btn-default.pull-right.next{ "ng-disabled"=>"currentPage >= total_objects/pageSize - 1 || loadingNext", "ng-click"=>"next()", style: "margin-left:3px" }
				%i.fa.fa-circle-o-notch.fa-spin{ 'ng-show' => "loadingNext" }
				%i.fa.fa-arrow-right{ 'ng-show' => "!loadingNext" }
			%a.btn.btn-default.pull-right.last{'ng-disabled'=>"currentPage == 0 || loadingLast", "ng-click"=>"last()"}
				%i.fa.fa-circle-o-notch.fa-spin{ 'ng-show' => "loadingLast" }
				%i.fa.fa-arrow-left{ 'ng-show' => "!loadingLast" }
	.panel-body#grid{ style: "border-right: 1px solid #e7e7e7;padding-left: 0px;padding-right: 0px;border-top-width: 36px;" }	
		%table.grid{style: "width:100%;"}
			%tbody
				%tr{ class: "select-{{object.checked}}", "ng-click" => "show_object(object)", :id => "row-{{object.id}}", "ng-repeat" => "object in objects | startFrom:currentPage*pageSize | limitTo:pageSize"}
					- if can? :delete, User
						%td{ width: "1px;" }
							.checkboxFour
								%input.checkboxFourInput{:id => "check-{{object.id}}", :type => "checkbox", "ng-model" => "object.checked", "ng-click" => "selected(object); $event.stopPorpagation();" }
								%label{ for: "check-{{object.id}}" }
									%span
					%td
						= link_to "{{show_path(object.id)}}", style: "width:100%;" do
							{{ object.name }}
				%tr{"ng-show" => "!objects.length"}
					%td{:style => "width:100%"}
						%center
							%i.fa.fa-frown-o
							No hay Solicitudes de Presupuesto.

app/views/brands/edit.html.haml
%h1 Editing brand

= render 'form'

= link_to 'Show', @brand
\|
= link_to 'Back', brands_path

app/views/brands/index.html.haml
= content_for(:title, "Admin - Branding")

.view-lg-md.hidden-xs.hidden-sm
  = render "view_lg_md"
.view-sm-xs.hidden-lg.hidden-md
  = render "view_sm_xs"

app/views/brands/new.html.haml
= render 'form'

app/views/brands/show.html.haml
= content_for(:title, "Admin - Branding | #{@brand.name}")
- flash.each do |name, msg|
	- if msg.is_a?(String)
		%div.hidden-xs{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}", id:"message_alerts"}
			%button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
			= content_tag :div, msg, :id => "flash_#{name}"
%div
	.panel.panel-default{style:"margin-top:50px"}
		.panel-heading#heading-show{style:"padding-top:5px"}
			.actions
				.title.pull-left{ style: "margin-top:8px;" }
					%i.fa.fa-user
					Solicitud de Presupuesto - 
					= @brand.id
				- if can? :destroy, User
					= link_to brand_path(@brand), title: t('admin.actions.delete'), :method => :delete, :data => { :confirm => '¿Estas seguro de querer eliminar este usuario?' }, class: "btn btn-default btn-action pull-right" do
						%i.fa.fa-remove
				- if can? :edit, User
					= link_to  edit_brand_path(@brand), title: t('admin.actions.edit'), class: "btn btn-default btn-action pull-right", style: "margin-right:3px;" do
						%i.fa.fa-pencil		

		.panel-body#body-show
			%label= 'Nombre y Apellido o Razón Social: '
			= @brand.name
			%br/
			%label= 'Email: '
			= @brand.email
			%br/
			%label= 'Número de Teléfono: '
			= @brand.telephone
			%br/
			%label= 'Tipo de Evento: '
			= @brand.brand_name
			%br/
			.col-lg-4.col-md-4.col-sm-4.col-xs-4
				%label IDENTIDAD CORPORATIVA
				%br/
				%div{style: "margin-left: 20px;"}
					= @brand.logo ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
					%label Logotipo
					%br/
					= @brand.tdp ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
					%label TDP
					%br/
					= @brand.envelope ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
					%label Sobre
					%br/
					= @brand.folder ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
					%label Carpeta
					%br/
					= @brand.email_signature ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
					%label Firma de Correo Electrónico
					%br/
					= @brand.products_menu ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
					%label Menú de Productos
					%br/
					= @brand.brand_menu ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
					%label Manual de Marca
					%br/
					= @brand.letterhead ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
					%label Hoja Membretada
					%br/
					= @brand.notebook ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
					%label Libreta
					%br/
					= @brand.carnet ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
					%label Carnet
					%br/
					= @brand.bill ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
					%label Factura
					%br/
					= @brand.uniform ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
					%label Uniforme
					%br/
					= @brand.brochure ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
					%label Brochure de Servicios
					%br/
					- if @brand.other_corp != ""
						%label Otro: 
						= @brand.other_corp
						%br/
			.col-lg-4.col-md-4.col-sm-4.col-xs-4
				%label MATERIAL P.O.P
				%br/
				%div{style: "margin-left: 20px;"}
					= @brand.pens ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
					%label Bolígrafos
					%br/
					= @brand.calendars ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
					%label Calendarios
					%br/
					= @brand.mouse_pad ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
					%label Mouse Pads
					%br/
					= @brand.disposable_ids ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
					%label Identificadores Desechables
					%br/
					= @brand.resin_ids ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
					%label Identificadores con Resina
					%br/
					= @brand.mugs ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
					%label Tazas/Mugs
					%br/
					= @brand.coolers ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
					%label Coolers
					%br/
					= @brand.key_chain ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
					%label Llaveros
					%br/
					= @brand.hats ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
					%label Gorras
					%br/
					= @brand.t_shirts ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
					%label Franelas
					%br/
					= @brand.stickers ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
					%label Stickers
					%br/
					- if @brand.other_pop != ""
						%label Otro: 
						= @brand.other_pop
						%br/
			.col-lg-4.col-md-4.col-sm-4.col-xs-4
				%label MATERIAL IMPRESO
				%br/
				%div{style: "margin-left: 20px;"}
					= @brand.poster_half_a4 ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
					%label Volante Media Carta
					%br/
					= @brand.poster_quarter_a4 ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
					%label Volante 1/4 Carta
					%br/
					= @brand.poster ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
					%label Afiche
					%br/
					= @brand.press_full ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
					%label Aviso de prensa pag. Completa
					%br/
					= @brand.press_double ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
					%label Aviso de prensa Doble Página
					%br/
					= @brand.press_half ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
					%label Aviso de prensa 1/2
					%br/
					= @brand.press_quarter ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
					%label Aviso de prensa 1/4
					%br/
					= @brand.press_eights ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
					%label Aviso de prensa 1/8
					%br/
					= @brand.pennon ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
					%label Pendón
					%br/
					= @brand.banner ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
					%label Pancarta 5x1mts
					%br/
					= @brand.backing ? "<i class='fa fa-check-circle'></i>".html_safe : "<i class='fa fa-close'></i>".html_safe
					%label Backing
					= @brand.backing
					%br/
					- if @brand.other_printed != ""
						%label Otro: 
						= @brand.other_printed
						%br/